content:
  - name: docs
    label: Documentation
    type: collection
    path: src/docs
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }