media:
  input: src/media
  output: /media
content:
  - name: docs
    label: Documentation
    type: collection
    path: src/docs
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }

  - name: colors
    label: Colors
    type: collection
    path: src/colors
    filename: "color_{primary}.md"
    view:
      fields: [ color, title ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: color, label: Color, type: color}
      
  - name: authors
    label: Authors
    type: collection
    path: src/authors
    filename: "author_{primary}.md"
    view:
      fields: [ image, name ]
    fields:
      - { name: name, label: Name, type: string, required: true }
      - { name: photo, label: Image, type: image }
      - name: fav-color
        label: Favourite Colour
        type: dropdown
        options: 
          collection:
            path: src/colors
            name: colors
      - { name: description, label: Description, type: text }
      - { name: body, label: Bio, type: rich-text }

  - label: Home page
    path: src/index.njk
    name: homepage
    type: file
    fields:
      - name: select
        type: select
        options: 
          values:
            - {value: item1, label: Item 1 } 
            - {value: item2, label: Item 2 } 
            - {value: item3, label: Item 3 } 
      - name: dropdownCollection
        type: dropdown
        options: 
          collection:
            path: src/docs
            name: docs
      - name: dropdownValues
        type: dropdown
        options: 
          values:
            - {value: item1, label: Item 1, other: A } 
            - {value: item2, label: Item 2, test: B } 
            - {value: item3, label: Item 3, lol: C } 
      - name: dropdownStrings
        type: dropdown
        options: 
          values: [Item 1, Item 2,  Item 3] 
      - { name: md, type: rich-text, }
      - { name: color, type: color, }
      - name: colors
        label: Colors
        type: object
        list: true
        fields:
          - { name: name, type: string, }
          - { name: color, type: color, }
      - { name: number, type: number, }
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - name: promotion
        label: Promotion
        type: object
        fields:
          - { name: text, label: Text, type: string }
          - { name: url, label: URL, type: string }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - name: features
        label: Features
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - name: entries
            label: Entries
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: string }
              - { name: icon, label: Icon, type: string }
              - { name: soon, label: Soon, type: boolean }
      - name: faq
        label: FAQ
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - name: entries
            label: Entries
            type: object
            list: true
            fields:
              - { name: question, label: Question, type: string }
              - { name: answer, label: Answer, type: text, options: { rows: 5 } }
      - { name: body, label: Body, type: code, options: { format: html} }
